### ISSUE TITLE
How did you get the SpriteFont scaling issues fixed?

### ISSUE THREAD

**Issue by shanedroid32** [Colbydude/FosterPlatformer#1]
I was just curious what your fix was for this. 

I tried using a couple different fonts and none of them seemed to look very crisp, regardless of what size I make them.

Any suggestions would be awesome.

Thanks!

**Comment by Colbydude** [comment]
Hiya! I unfortunately don't have a super good answer for this. 😅 

I basically just kept trying values until the font looked like it wasn't being scaled weird and added extra "\n"s to help with spacing and kinda lucked out. I haven't dug in to learning Foster deep enough to really diagnose the issue. Didn't want to spend more than the 15 hours Noel did initially putting it together.

It might be worth putting together a demo of the font scaling issues with various fonts and opening an issue/investing and opening a PR on the main Foster repo.

Best of luck!
